package com.tale.mybatis.dao.read.mbg;

import com.tale.model.po.mbg.ReportData;
import com.tale.model.po.mbg.ReportDataExample;
import java.util.List;

public interface MBGReportDataReadDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int countByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    List<ReportData> selectByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    ReportData selectByPrimaryKey(Integer id);
}