package com.tale.mybatis.dao.write.mbg;

import com.tale.model.po.mbg.ReportData;
import com.tale.model.po.mbg.ReportDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGReportDataWriteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int countByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int deleteByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int insert(ReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int insertSelective(ReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    List<ReportData> selectByExample(ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    ReportData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportData record, @Param("example") ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportData record, @Param("example") ReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportData record);
}